<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BiblioTarApp.DateContext\BiblioTarApp.DataContext.csproj" />
    <ProjectReference Include="..\BiblioTarApp.Services\BiblioTarApp.Services.csproj" />
    <ProjectReference Include="..\BiblioTarApp\BiblioTarApp.csproj" />
  </ItemGroup>

</Project>