// <auto-generated />
using System;
using BiblioTarApp.DataContext.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BiblioTarApp.DataContext.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260301010841_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BiblioTarApp.DataContext.Entites.Buntetes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Ar")
                        .HasColumnType("int");

                    b.Property<DateTime>("BuntetesIdeje")
                        .HasColumnType("datetime2");

                    b.Property<int>("FelhasznaloId")
                        .HasColumnType("int");

                    b.Property<bool>("FizetesiStatusz")
                        .HasColumnType("bit");

                    b.Property<int>("FoglalasId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FelhasznaloId");

                    b.HasIndex("FoglalasId")
                        .IsUnique();

                    b.ToTable("Buntetesek");
                });

            modelBuilder.Entity("BiblioTarApp.DataContext.Entites.Felhasznalo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jelszo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Felhasznalok");
                });

            modelBuilder.Entity("BiblioTarApp.DataContext.Entites.Foglalas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FelhasznaloId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FoglalasIdeje")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Hatarido")
                        .HasColumnType("datetime2");

                    b.Property<int>("KonyvId")
                        .HasColumnType("int");

                    b.Property<int>("MeghosszabbitasiLehetosegek")
                        .HasColumnType("int");

                    b.Property<int>("Statusz")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FelhasznaloId");

                    b.HasIndex("KonyvId");

                    b.ToTable("Foglalasok");
                });

            modelBuilder.Entity("BiblioTarApp.DataContext.Entites.Kolcsonzes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FelhasznaloId")
                        .HasColumnType("int");

                    b.Property<DateTime>("KolcsozesIdeje")
                        .HasColumnType("datetime2");

                    b.Property<int>("Statusz")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("FelhasznaloId");

                    b.ToTable("Kolcsonzesek");
                });

            modelBuilder.Entity("BiblioTarApp.DataContext.Entites.Konyv", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Allapot")
                        .HasColumnType("int");

                    b.Property<string>("Cim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ertelekes")
                        .HasColumnType("int");

                    b.Property<string>("Kategoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PublikalasIdeje")
                        .HasColumnType("datetime2");

                    b.Property<int>("Statusz")
                        .HasColumnType("int");

                    b.Property<string>("Szerzo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Konyvek");
                });

            modelBuilder.Entity("BiblioTarApp.DataContext.Entites.Lakcim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("FelhasznaloId")
                        .HasColumnType("int");

                    b.Property<int>("Iranyitoszam")
                        .HasColumnType("int");

                    b.Property<string>("Utca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Varos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hazszam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FelhasznaloId");

                    b.ToTable("Lakimcek");
                });

            modelBuilder.Entity("BiblioTarApp.DataContext.Entites.Buntetes", b =>
                {
                    b.HasOne("BiblioTarApp.DataContext.Entites.Felhasznalo", "Felhasznalo")
                        .WithMany()
                        .HasForeignKey("FelhasznaloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BiblioTarApp.DataContext.Entites.Foglalas", "Foglalas")
                        .WithOne("Szamla")
                        .HasForeignKey("BiblioTarApp.DataContext.Entites.Buntetes", "FoglalasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Felhasznalo");

                    b.Navigation("Foglalas");
                });

            modelBuilder.Entity("BiblioTarApp.DataContext.Entites.Foglalas", b =>
                {
                    b.HasOne("BiblioTarApp.DataContext.Entites.Felhasznalo", "Felhasznalo")
                        .WithMany()
                        .HasForeignKey("FelhasznaloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BiblioTarApp.DataContext.Entites.Konyv", "Konyv")
                        .WithMany()
                        .HasForeignKey("KonyvId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Felhasznalo");

                    b.Navigation("Konyv");
                });

            modelBuilder.Entity("BiblioTarApp.DataContext.Entites.Kolcsonzes", b =>
                {
                    b.HasOne("BiblioTarApp.DataContext.Entites.Konyv", "Konyv")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BiblioTarApp.DataContext.Entites.Felhasznalo", "Felhasznalo")
                        .WithMany()
                        .HasForeignKey("FelhasznaloId");

                    b.Navigation("Felhasznalo");

                    b.Navigation("Konyv");
                });

            modelBuilder.Entity("BiblioTarApp.DataContext.Entites.Lakcim", b =>
                {
                    b.HasOne("BiblioTarApp.DataContext.Entites.Felhasznalo", "Felhasznalo")
                        .WithMany("Lakcim")
                        .HasForeignKey("FelhasznaloId");

                    b.Navigation("Felhasznalo");
                });

            modelBuilder.Entity("BiblioTarApp.DataContext.Entites.Felhasznalo", b =>
                {
                    b.Navigation("Lakcim");
                });

            modelBuilder.Entity("BiblioTarApp.DataContext.Entites.Foglalas", b =>
                {
                    b.Navigation("Szamla")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
